"""empty message

Revision ID: 210ed13ceeb1
Revises: 
Create Date: 2023-11-06 21:41:48.193788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210ed13ceeb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
